[package]
name = "wake"
version = "0.1.0"
authors = ["Kayla Firestack <me@stackfire.io>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
wakey = "0.3.0"

[features]
