[package]
name = "wake"
version = "0.1.0"
authors = ["Kayla Firestack <me@stackfire.io>"]
edition = "2018"

[dependencies]
wakey = { git="https://github.com/firestack/wakey.git" }
structopt = "0.2.18"
