[package]
name = "wake"
version = "0.1.0"
authors = ["Kayla Firestack <me@stackfire.io>"]
edition = "2021"

[dependencies]
wakey = { git="https://github.com/firestack/wakey.git" }
clap = { version = "4.5.1", features = ["derive"] }

[features]
